// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPbGo7UNseuNzbcNTl58PNEi5vQCUlTMY',
    appId: '1:291225163539:web:2eff627bf16cd0f752ece6',
    messagingSenderId: '291225163539',
    projectId: 'edu-link-42c67',
    authDomain: 'edu-link-42c67.firebaseapp.com',
    storageBucket: 'edu-link-42c67.firebasestorage.app',
    measurementId: 'G-FYVVHJFQ7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkPO7mwqLAxGtj1Y1bl3P0AGCJ7SAgj-U',
    appId: '1:291225163539:android:a4e06011660f84cb52ece6',
    messagingSenderId: '291225163539',
    projectId: 'edu-link-42c67',
    storageBucket: 'edu-link-42c67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeNEPla2bBB7ULnKkGzGDzUB7jGlJYz3g',
    appId: '1:291225163539:ios:a7366b2362a1792352ece6',
    messagingSenderId: '291225163539',
    projectId: 'edu-link-42c67',
    storageBucket: 'edu-link-42c67.firebasestorage.app',
    iosBundleId: 'com.example.eduLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeNEPla2bBB7ULnKkGzGDzUB7jGlJYz3g',
    appId: '1:291225163539:ios:a7366b2362a1792352ece6',
    messagingSenderId: '291225163539',
    projectId: 'edu-link-42c67',
    storageBucket: 'edu-link-42c67.firebasestorage.app',
    iosBundleId: 'com.example.eduLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPbGo7UNseuNzbcNTl58PNEi5vQCUlTMY',
    appId: '1:291225163539:web:263f921d133d572352ece6',
    messagingSenderId: '291225163539',
    projectId: 'edu-link-42c67',
    authDomain: 'edu-link-42c67.firebaseapp.com',
    storageBucket: 'edu-link-42c67.firebasestorage.app',
    measurementId: 'G-7B6H0P7QM4',
  );
}
